name: lserial
description: "High-throughput cross-platform communication debug tool."
publish_to: 'none'

version: 1.0.8+9

environment:
  sdk: ^3.9.0

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.4.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  universal_ble: ^1.2.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC-UI.ttf
